package com.leidos.dataparser.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;

/**
 * Created by rushk1 on 5/12/2015.
 */
public class AboutForm {
    private JTextPane aboutText;
    private JPanel panel1;
    private static final String ABOUT_MESSAGE = "FHWA Data Processing Application by Leidos\n" +
            "Data Processing Application developed by Leidos at the Request of FHWA 2015. Processes raw PCAP formatted" +
            " connected vehicle data into more usable CSV output. Released as open source on the US DOT Open Source" +
            " Software Portal.";

    public AboutForm() {
        StyleContext context = new StyleContext();
        StyledDocument document = new DefaultStyledDocument(context);
        Style style = context.getStyle(StyleContext.DEFAULT_STYLE);
        StyleConstants.setAlignment(style, StyleConstants.ALIGN_LEFT);
        StyleConstants.setFontSize(style, 14);
        StyleConstants.setSpaceAbove(style, 4);
        StyleConstants.setSpaceBelow(style, 4);

        try {
            document.insertString(document.getLength(), ABOUT_MESSAGE, style);
        } catch (BadLocationException e) {
            e.printStackTrace();
        }

        aboutText.setDocument(document);
        aboutText.setEditable(false);
    }

    public JPanel getContent() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setPreferredSize(new Dimension(200, 300));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        aboutText = new JTextPane();
        aboutText.setText("");
        scrollPane1.setViewportView(aboutText);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
